In [3]:
import pandas as pd

df_game_skater_stats = pd.read_csv(r"C:\Users\zacle\Desktop\Serene\Project\NHL\ETL\extract\raw_data\game_skater_stats.csv")
df_game_skater_stats.head()
df_game_skater_stats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 945830 entries, 0 to 945829
Data columns (total 22 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   game_id               945830 non-null  int64
 1   player_id             945830 non-null  int64
 2   team_id               945830 non-null  int64
 3   timeOnIce             945830 non-null  int64
 4   assists               945830 non-null  int64
 5   goals                 945830 non-null  int64
 6   shots                 945830 non-null  int64
 7   hits                  547723 non-null  float64
 8   powerPlayGoals        945830 non-null  int64
 9   powerPlayAssists      945830 non-null  int64
 10  penaltyMinutes        945830 non-null  int64
 11  faceOffWins           945830 non-null  int64
 12  faceoffTaken          945830 non-null  int64
 13  takeaways             547723 non-null  float64
 14  giveaways             547723 non-null  float64
 15  shortHandedGoals      945830 non-null  int64
 16  shortHandedAssists    945830 non-null  int64
 17  blocked               547723 non-null  float64
 18  plusMinus             945830 non-null  int64
 19  evenTimeOnIce         945830 non-null  int64
 20  shortHandedTimeOnIce  945830 non-null  int64
 21  powerPlayTimeOnIce    945830 non-null  int64
dtypes: float64(4), int64(18)
memory usage: 158.8 MB

In [5]:
# Create a new dataframe from df_game_skater_stats (copying original to preserve data)
df_clean_game_skater_stats = df_game_skater_stats.copy()

In [7]:
#Rename columns for consistency

import re

# Function to add an underscore before uppercase letters and convert to lowercase
def rename_columns(col_name):
    return re.sub(r'([a-z0-9])([A-Z])', r'\1_\2', col_name).lower()

# Apply the function to all column names
df_clean_game_skater_stats.columns = [rename_columns(col) for col in df_clean_game_skater_stats.columns]

# Rename the columns 
df_clean_game_skater_stats = df_clean_game_skater_stats.rename(columns={'faceoff_taken': 'face_off_taken'})

df_clean_game_skater_stats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 945830 entries, 0 to 945829
Data columns (total 22 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   game_id                   945830 non-null  int64
 1   player_id                 945830 non-null  int64
 2   team_id                   945830 non-null  int64
 3   time_on_ice               945830 non-null  int64
 4   assists                   945830 non-null  int64
 5   goals                     945830 non-null  int64
 6   shots                     945830 non-null  int64
 7   hits                      547723 non-null  float64
 8   power_play_goals          945830 non-null  int64
 9   power_play_assists        945830 non-null  int64
 10  penalty_minutes           945830 non-null  int64
 11  face_off_wins             945830 non-null  int64
 12  face_off_taken            945830 non-null  int64
 13  takeaways                 547723 non-null  float64
 14  giveaways                 547723 non-null  float64
 15  short_handed_goals        945830 non-null  int64
 16  short_handed_assists      945830 non-null  int64
 17  blocked                   547723 non-null  float64
 18  plus_minus                945830 non-null  int64
 19  even_time_on_ice          945830 non-null  int64
 20  short_handed_time_on_ice  945830 non-null  int64
 21  power_play_time_on_ice    945830 non-null  int64
dtypes: float64(4), int64(18)
memory usage: 158.8 MB

In [9]:
# Null - All - check for missing or null values entire dataset
df_clean_game_skater_stats.isnull().sum()

game_id                          0
player_id                        0
team_id                          0
time_on_ice                      0
assists                          0
goals                            0
shots                            0
hits                        398107
power_play_goals                 0
power_play_assists               0
penalty_minutes                  0
face_off_wins                    0
face_off_taken                   0
takeaways                   398107
giveaways                   398107
short_handed_goals               0
short_handed_assists             0
blocked                     398107
plus_minus                       0
even_time_on_ice                 0
short_handed_time_on_ice         0
power_play_time_on_ice           0
dtype: int64

In [11]:
# duplicates : 76841
# Count unique 'game_id' values
unique_ids = df_clean_game_skater_stats['game_id'].nunique()

# Count total number of rows
total_rows = len(df_clean_game_skater_stats)

# Display the results
print(f"Unique game_ids: {unique_ids}")
print(f"Total rows: {total_rows}")
print(f"There are {total_rows - unique_ids} rows with duplicates.")

Unique game_ids: 23721
Total rows: 945830
There are 922109 rows with duplicates.

In [13]:
# 8738 duplicate rows
# Additional Duplicate Check for 'game_id', 'player_id' combinations
duplicates_id = df_clean_game_skater_stats[df_clean_game_skater_stats.duplicated(subset=['game_id', 'player_id'], keep=False)]

# Sort rows with duplicated results in ascending order by 'game_id', 'player_id'
duplicates_id_sorted = duplicates_id.sort_values(by=['game_id', 'player_id'], ascending=True)

# Count total number of rows with duplicates based on 'game_id', 'player_id'
total_duplicates = df_clean_game_skater_stats.duplicated(subset=['game_id', 'player_id'], keep=False).sum()

# Count the unique combinations of 'game_id', 'player_id'
unique_combinations = df_clean_game_skater_stats[['game_id', 'player_id']].drop_duplicates().shape[0]

# Count total number of rows
total_rows = len(df_clean_game_skater_stats)

# Display the results
print(f"Unique 'game_id', 'player_id' combinations: {unique_combinations}")
print(f"Total rows: {total_rows}")
print(f"There are {total_rows - unique_combinations} rows with duplicates based on 'game_id', 'player_id'.")

# Display the sorted duplicates for further review
print("Sorted Duplicates based on 'game_id', 'player_id':")
print(duplicates_id_sorted[['game_id', 'player_id']])
duplicates_id_sorted.head(10)

Unique 'game_id', 'player_id' combinations: 853404
Total rows: 945830
There are 92426 rows with duplicates based on 'game_id', 'player_id'.
Sorted Duplicates based on 'game_id', 'player_id':
           game_id  player_id
848019  2018020001    8466139
848163  2018020001    8466139
848003  2018020001    8468493
848147  2018020001    8468493
847984  2018020001    8473507
...            ...        ...
816124  2019040653    8480012
816063  2019040653    8480800
816117  2019040653    8480800
816055  2019040653    8480801
816109  2019040653    8480801

[184852 rows x 2 columns]

,game_id,player_id,team_id,time_on_ice,assists,goals,shots,hits,power_play_goals,power_play_assists,...,face_off_taken,takeaways,giveaways,short_handed_goals,short_handed_assists,blocked,plus_minus,even_time_on_ice,short_handed_time_on_ice,power_play_time_on_ice
848019,2018020001,8466139,10,1011,1,0,3,0.0,0,0,...,0,0.0,0.0,0,0,4.0,0,927,0,84
848163,2018020001,8466139,10,1011,1,0,3,0.0,0,0,...,0,0.0,0.0,0,0,4.0,0,927,0,84
848003,2018020001,8468493,10,1208,0,0,1,1.0,0,0,...,0,0.0,2.0,0,0,2.0,0,984,219,5
848147,2018020001,8468493,10,1208,0,0,1,1.0,0,0,...,0,0.0,2.0,0,0,2.0,0,984,219,5
847984,2018020001,8473507,8,1437,0,0,3,3.0,0,0,...,0,2.0,1.0,0,0,1.0,-1,1105,82,250
848128,2018020001,8473507,8,1437,0,0,3,3.0,0,0,...,0,2.0,1.0,0,0,1.0,-1,1105,82,250
847987,2018020001,8474038,8,883,1,0,2,3.0,0,0,...,1,0.0,0.0,0,0,1.0,1,788,65,30
848131,2018020001,8474038,8,883,1,0,2,3.0,0,0,...,1,0.0,0.0,0,0,1.0,1,788,65,30
848016,2018020001,8474581,10,1349,1,0,0,2.0,0,0,...,0,0.0,3.0,0,0,1.0,1,1155,72,122
848160,2018020001,8474581,10,1349,1,0,0,2.0,0,0,...,0,0.0,3.0,0,0,1.0,1,1155,72,122

In [15]:
# 8738 duplicate rows
# Additional Duplicate Check for 'game_id', 'player_id', 'team_id' combinations same as with 'game_id' and 'player_id'
duplicates_id = df_clean_game_skater_stats[df_clean_game_skater_stats.duplicated(subset=['game_id', 'player_id', 'team_id'], keep=False)]

# Sort rows with duplicated results in ascending order by 'game_id', 'player_id', 'team_id'
duplicates_id_sorted = duplicates_id.sort_values(by=['game_id', 'player_id', 'team_id'], ascending=True)

# Count total number of rows with duplicates based on 'game_id', 'player_id', 'team_id'
total_duplicates = df_clean_game_skater_stats.duplicated(subset=['game_id', 'player_id', 'team_id'], keep=False).sum()

# Count the unique combinations of 'game_id', 'player_id', 'team_id'
unique_combinations = df_clean_game_skater_stats[['game_id', 'player_id', 'team_id']].drop_duplicates().shape[0]

# Count total number of rows
total_rows = len(df_clean_game_skater_stats)

# Display the results
print(f"Unique 'game_id', 'player_id', 'team_id' combinations: {unique_combinations}")
print(f"Total rows: {total_rows}")
print(f"There are {total_rows - unique_combinations} rows with duplicates based on 'game_id', 'player_id', 'team_id'.")

# Display the sorted duplicates for further review
print("Sorted Duplicates based on 'game_id', 'player_id', 'team_id':")
print(duplicates_id_sorted[['game_id', 'player_id', 'team_id']])
duplicates_id_sorted.head(10)

Unique 'game_id', 'player_id', 'team_id' combinations: 853404
Total rows: 945830
There are 92426 rows with duplicates based on 'game_id', 'player_id', 'team_id'.
Sorted Duplicates based on 'game_id', 'player_id', 'team_id':
           game_id  player_id  team_id
848019  2018020001    8466139       10
848163  2018020001    8466139       10
848003  2018020001    8468493       10
848147  2018020001    8468493       10
847984  2018020001    8473507        8
...            ...        ...      ...
816124  2019040653    8480012       90
816063  2019040653    8480800       90
816117  2019040653    8480800       90
816055  2019040653    8480801       87
816109  2019040653    8480801       87

[184852 rows x 3 columns]

,game_id,player_id,team_id,time_on_ice,assists,goals,shots,hits,power_play_goals,power_play_assists,...,face_off_taken,takeaways,giveaways,short_handed_goals,short_handed_assists,blocked,plus_minus,even_time_on_ice,short_handed_time_on_ice,power_play_time_on_ice
848019,2018020001,8466139,10,1011,1,0,3,0.0,0,0,...,0,0.0,0.0,0,0,4.0,0,927,0,84
848163,2018020001,8466139,10,1011,1,0,3,0.0,0,0,...,0,0.0,0.0,0,0,4.0,0,927,0,84
848003,2018020001,8468493,10,1208,0,0,1,1.0,0,0,...,0,0.0,2.0,0,0,2.0,0,984,219,5
848147,2018020001,8468493,10,1208,0,0,1,1.0,0,0,...,0,0.0,2.0,0,0,2.0,0,984,219,5
847984,2018020001,8473507,8,1437,0,0,3,3.0,0,0,...,0,2.0,1.0,0,0,1.0,-1,1105,82,250
848128,2018020001,8473507,8,1437,0,0,3,3.0,0,0,...,0,2.0,1.0,0,0,1.0,-1,1105,82,250
847987,2018020001,8474038,8,883,1,0,2,3.0,0,0,...,1,0.0,0.0,0,0,1.0,1,788,65,30
848131,2018020001,8474038,8,883,1,0,2,3.0,0,0,...,1,0.0,0.0,0,0,1.0,1,788,65,30
848016,2018020001,8474581,10,1349,1,0,0,2.0,0,0,...,0,0.0,3.0,0,0,1.0,1,1155,72,122
848160,2018020001,8474581,10,1349,1,0,0,2.0,0,0,...,0,0.0,3.0,0,0,1.0,1,1155,72,122

In [17]:
# Upon visual inspection of the 1st 10 rows shows that there are 8738 rows with true duplicates. 
# Remove duplicates based on 'game_id', 'player_id', 'team_id'(just to to be sure!)
df_clean_game_skater_stats = df_clean_game_skater_stats.drop_duplicates(subset=['game_id', 'player_id', 'team_id'], keep='first')

# Display the cleaned dataframe (first 30 rows as an example)
df_clean_game_skater_stats.head(10)
df_clean_game_skater_stats.info()

<class 'pandas.core.frame.DataFrame'>
Index: 853404 entries, 0 to 945793
Data columns (total 22 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   game_id                   853404 non-null  int64
 1   player_id                 853404 non-null  int64
 2   team_id                   853404 non-null  int64
 3   time_on_ice               853404 non-null  int64
 4   assists                   853404 non-null  int64
 5   goals                     853404 non-null  int64
 6   shots                     853404 non-null  int64
 7   hits                      455297 non-null  float64
 8   power_play_goals          853404 non-null  int64
 9   power_play_assists        853404 non-null  int64
 10  penalty_minutes           853404 non-null  int64
 11  face_off_wins             853404 non-null  int64
 12  face_off_taken            853404 non-null  int64
 13  takeaways                 455297 non-null  float64
 14  giveaways                 455297 non-null  float64
 15  short_handed_goals        853404 non-null  int64
 16  short_handed_assists      853404 non-null  int64
 17  blocked                   455297 non-null  float64
 18  plus_minus                853404 non-null  int64
 19  even_time_on_ice          853404 non-null  int64
 20  short_handed_time_on_ice  853404 non-null  int64
 21  power_play_time_on_ice    853404 non-null  int64
dtypes: float64(4), int64(18)
memory usage: 149.8 MB

In [19]:
# Duplicate Check : Duplicates resolved!
# Additional Duplicate Check for 'game_id', 'player_id' combinations
duplicates_id = df_clean_game_skater_stats[df_clean_game_skater_stats.duplicated(subset=['game_id', 'player_id'], keep=False)]

# Sort rows with duplicated results in ascending order by 'game_id', 'player_id'
duplicates_id_sorted = duplicates_id.sort_values(by=['game_id', 'player_id'], ascending=True)

# Count total number of rows with duplicates based on 'game_id', 'player_id'
total_duplicates = df_clean_game_skater_stats.duplicated(subset=['game_id', 'player_id'], keep=False).sum()

# Count the unique combinations of 'game_id', 'player_id'
unique_combinations = df_clean_game_skater_stats[['game_id', 'player_id']].drop_duplicates().shape[0]

# Count total number of rows
total_rows = len(df_clean_game_skater_stats)

# Display the results
print(f"Unique 'game_id', 'player_id' combinations: {unique_combinations}")
print(f"Total rows: {total_rows}")
print(f"There are {total_rows - unique_combinations} rows with duplicates based on 'game_id', 'player_id'.")

# Display the sorted duplicates for further review
print("Sorted Duplicates based on 'game_id', 'player_id':")
print(duplicates_id_sorted[['game_id', 'player_id']])
duplicates_id_sorted.head(30)

Unique 'game_id', 'player_id' combinations: 853404
Total rows: 853404
There are 0 rows with duplicates based on 'game_id', 'player_id'.
Sorted Duplicates based on 'game_id', 'player_id':
Empty DataFrame
Columns: [game_id, player_id]
Index: []

Empty DataFrame
Columns: [game_id, player_id, team_id, time_on_ice, assists, goals, shots, hits, power_play_goals, power_play_assists, penalty_minutes, face_off_wins, face_off_taken, takeaways, giveaways, short_handed_goals, short_handed_assists, blocked, plus_minus, even_time_on_ice, short_handed_time_on_ice, power_play_time_on_ice]
Index: []

[0 rows x 22 columns]

In [21]:
# Change data type syntax - df['column_name'] = df['column_name'].astype('desired_data_type')
df_clean_game_skater_stats['game_id'] = df_clean_game_skater_stats['game_id'].astype(str)
df_clean_game_skater_stats['player_id'] = df_clean_game_skater_stats['player_id'].astype(str)
df_clean_game_skater_stats['team_id'] = df_clean_game_skater_stats['team_id'].astype(str)

df_clean_game_skater_stats.info()

<class 'pandas.core.frame.DataFrame'>
Index: 853404 entries, 0 to 945793
Data columns (total 22 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   game_id                   853404 non-null  object
 1   player_id                 853404 non-null  object
 2   team_id                   853404 non-null  object
 3   time_on_ice               853404 non-null  int64
 4   assists                   853404 non-null  int64
 5   goals                     853404 non-null  int64
 6   shots                     853404 non-null  int64
 7   hits                      455297 non-null  float64
 8   power_play_goals          853404 non-null  int64
 9   power_play_assists        853404 non-null  int64
 10  penalty_minutes           853404 non-null  int64
 11  face_off_wins             853404 non-null  int64
 12  face_off_taken            853404 non-null  int64
 13  takeaways                 455297 non-null  float64
 14  giveaways                 455297 non-null  float64
 15  short_handed_goals        853404 non-null  int64
 16  short_handed_assists      853404 non-null  int64
 17  blocked                   455297 non-null  float64
 18  plus_minus                853404 non-null  int64
 19  even_time_on_ice          853404 non-null  int64
 20  short_handed_time_on_ice  853404 non-null  int64
 21  power_play_time_on_ice    853404 non-null  int64
dtypes: float64(4), int64(15), object(3)
memory usage: 149.8+ MB

In [23]:
#save file locally
df_clean_game_skater_stats.to_csv(r"C:\Users\zacle\Desktop\Serene\Project\NHL\ETL\clean\game_skater_stats.csv", index=False)