In [73]:
import pandas as pd

In [75]:
#understand the dataset
# primaryPosition: The player's primary position on the ice:
# RW: Right Wing
# LW: Left Wing
# C: Center
# D: Defense
# G: Goalie

df_player_info = pd.read_csv(r"C:\Users\zacle\Desktop\Serene\Project\NHL\ETL\extract\raw_data\player_info.csv")
df_player_info.head()
df_player_info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3925 entries, 0 to 3924
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   player_id           3925 non-null   int64
 1   firstName           3925 non-null   object
 2   lastName            3925 non-null   object
 3   nationality         3917 non-null   object
 4   birthCity           3920 non-null   object
 5   primaryPosition     3925 non-null   object
 6   birthDate           3925 non-null   object
 7   birthStateProvince  2802 non-null   object
 8   height              3922 non-null   object
 9   height_cm           3922 non-null   float64
 10  weight              3922 non-null   float64
 11  shootsCatches       3908 non-null   object
dtypes: float64(2), int64(1), object(9)
memory usage: 368.1+ KB

In [77]:
# Create a new dataframe from df_game_goalie_stats (copying original to preserve data)
df_clean_player_info = df_player_info.copy()

Rename Columns

In [80]:
#Rename columns for consistency 
#Function to add an underscore before uppercase letters and convert to lowercase
import re

def rename_columns(col_name):
    return re.sub(r'([a-z0-9])([A-Z])', r'\1_\2', col_name).lower()

# Apply the function to all column names
df_clean_player_info.columns = [rename_columns(col) for col in df_clean_player_info.columns]
df_clean_player_info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3925 entries, 0 to 3924
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   player_id             3925 non-null   int64
 1   first_name            3925 non-null   object
 2   last_name             3925 non-null   object
 3   nationality           3917 non-null   object
 4   birth_city            3920 non-null   object
 5   primary_position      3925 non-null   object
 6   birth_date            3925 non-null   object
 7   birth_state_province  2802 non-null   object
 8   height                3922 non-null   object
 9   height_cm             3922 non-null   float64
 10  weight                3922 non-null   float64
 11  shoots_catches        3908 non-null   object
dtypes: float64(2), int64(1), object(9)
memory usage: 368.1+ KB

Check Nulls

In [83]:
# Null - All - check for missing or null values entire dataset
df_clean_player_info.isnull().sum()

player_id                  0
first_name                 0
last_name                  0
nationality                8
birth_city                 5
primary_position           0
birth_date                 0
birth_state_province    1123
height                     3
height_cm                  3
weight                     3
shoots_catches            17
dtype: int64

In [91]:
#Replace null values of the birth_state_province column with 'unknown'
df_clean_player_info['birth_state_province'] = df_clean_player_info['birth_state_province'].fillna('unknown')

#Removing null value rows will result in a Foreign Key error in game_goalie_stats. 
#Keep null values for the other columns as the number is trivial
#df_clean_player_info = df_clean_player_info.dropna()

df_clean_player_info['weight'] = df_clean_player_info['weight'].fillna(0)  # Fill the value with 0 

df_clean_player_info['height_cm'] = df_clean_player_info['height_cm'].fillna(0)  # Fill the value with 0

df_clean_player_info.isnull().sum()

player_id                0
first_name               0
last_name                0
nationality              8
birth_city               5
primary_position         0
birth_date               0
birth_state_province     0
height                   3
height_cm                0
weight                   0
shoots_catches          17
dtype: int64

In [93]:
# duplicates : 0
# Count unique 'player_id' values
unique_ids = df_clean_player_info['player_id'].nunique()

# Count total number of rows
total_rows = len(df_clean_player_info)

# Display the results
print(f"Unique player_ids: {unique_ids}")
print(f"Total rows: {total_rows}")
print(f"There are {total_rows - unique_ids} rows with duplicates.")

Unique player_ids: 3925
Total rows: 3925
There are 0 rows with duplicates.

In [95]:
df_clean_player_info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3925 entries, 0 to 3924
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   player_id             3925 non-null   int64
 1   first_name            3925 non-null   object
 2   last_name             3925 non-null   object
 3   nationality           3917 non-null   object
 4   birth_city            3920 non-null   object
 5   primary_position      3925 non-null   object
 6   birth_date            3925 non-null   object
 7   birth_state_province  3925 non-null   object
 8   height                3922 non-null   object
 9   height_cm             3925 non-null   float64
 10  weight                3925 non-null   float64
 11  shoots_catches        3908 non-null   object
dtypes: float64(2), int64(1), object(9)
memory usage: 368.1+ KB

Change Data Type

In [98]:
# Change data type syntax - df['column_name'] = df['column_name'].astype('desired_data_type')
df_clean_player_info['player_id'] = df_clean_player_info['player_id'].astype(str)
df_clean_player_info['first_name'] = df_clean_player_info['first_name'].astype(str)

In [100]:
import numpy as np
# Ensure 'birth_date' is in datetime format, replacing invalid values with NaT
df_clean_player_info['birth_date'] = pd.to_datetime(df_clean_player_info['birth_date'], errors='coerce')

df_clean_player_info.info()
df_clean_player_info.head(3)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3925 entries, 0 to 3924
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   player_id             3925 non-null   object
 1   first_name            3925 non-null   object
 2   last_name             3925 non-null   object
 3   nationality           3917 non-null   object
 4   birth_city            3920 non-null   object
 5   primary_position      3925 non-null   object
 6   birth_date            3925 non-null   datetime64[ns]
 7   birth_state_province  3925 non-null   object
 8   height                3922 non-null   object
 9   height_cm             3925 non-null   float64
 10  weight                3925 non-null   float64
 11  shoots_catches        3908 non-null   object
dtypes: datetime64[ns](1), float64(2), object(9)
memory usage: 368.1+ KB

,player_id,first_name,last_name,nationality,birth_city,primary_position,birth_date,birth_state_province,height,height_cm,weight,shoots_catches
0,8466148,Marian,Hossa,SVK,Stará Lubovna,RW,1979-01-12 00:00:00,unknown,"6' 1""",185.42,207.0,L
1,8465058,Michal,Rozsival,CZE,Vlasim,D,1978-09-03 01:00:00,unknown,"6' 1""",185.42,210.0,R
2,8476906,Shayne,Gostisbehere,USA,Pembroke Pines,D,1993-04-20 01:00:00,FL,"5' 11""",180.34,180.0,L

In [102]:
print(df_clean_player_info.columns)

Index(['player_id', 'first_name', 'last_name', 'nationality', 'birth_city',
       'primary_position', 'birth_date', 'birth_state_province', 'height',
       'height_cm', 'weight', 'shoots_catches'],
      dtype='object')

In [104]:
#Convert weight from pounds to kilograms
df_clean_player_info['weight_kg'] = df_clean_player_info['weight'] * 0.453592

# Reorder columns to move 'weight_kg' to the 12th position
columns = list(df_clean_player_info.columns)
columns.insert(11, columns.pop(columns.index('weight_kg')))  # Move 'weight_kg' to position 12 (index 11)
df_clean_player_info = df_clean_player_info[columns]

# Print the DataFrame to verify
df_clean_player_info.head(5)

,player_id,first_name,last_name,nationality,birth_city,primary_position,birth_date,birth_state_province,height,height_cm,weight,weight_kg,shoots_catches
0,8466148,Marian,Hossa,SVK,Stará Lubovna,RW,1979-01-12 00:00:00,unknown,"6' 1""",185.42,207.0,93.893544,L
1,8465058,Michal,Rozsival,CZE,Vlasim,D,1978-09-03 01:00:00,unknown,"6' 1""",185.42,210.0,95.254320,R
2,8476906,Shayne,Gostisbehere,USA,Pembroke Pines,D,1993-04-20 01:00:00,FL,"5' 11""",180.34,180.0,81.646560,L
3,8466285,Brian,Campbell,CAN,Strathroy,D,1979-05-23 01:00:00,ON,"5' 10""",177.80,192.0,87.089664,L
4,8470607,Brent,Seabrook,CAN,Richmond,D,1985-04-20 01:00:00,BC,"6' 3""",190.50,220.0,99.790240,R

In [106]:
# grp discussion - 22 Jan 
# to remove the redundant columns for simplifying data - height (duplicate in string format) 

columns_to_remove = ['height', 'weight']  
df_clean_player_info = df_clean_player_info.drop(columns=columns_to_remove)
df_clean_player_info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3925 entries, 0 to 3924
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   player_id             3925 non-null   object
 1   first_name            3925 non-null   object
 2   last_name             3925 non-null   object
 3   nationality           3917 non-null   object
 4   birth_city            3920 non-null   object
 5   primary_position      3925 non-null   object
 6   birth_date            3925 non-null   datetime64[ns]
 7   birth_state_province  3925 non-null   object
 8   height_cm             3925 non-null   float64
 9   weight_kg             3925 non-null   float64
 10  shoots_catches        3908 non-null   object
dtypes: datetime64[ns](1), float64(2), object(8)
memory usage: 337.4+ KB

In [108]:
df_clean_player_info['first_name'] = df_clean_player_info['first_name'].astype(str)

max_length = df_clean_player_info['birth_state_province'].str.len().max()
print(max_length)  # Prints the maximum length of first names

7

In [110]:
df_clean_player_info.head(5)

,player_id,first_name,last_name,nationality,birth_city,primary_position,birth_date,birth_state_province,height_cm,weight_kg,shoots_catches
0,8466148,Marian,Hossa,SVK,Stará Lubovna,RW,1979-01-12 00:00:00,unknown,185.42,93.893544,L
1,8465058,Michal,Rozsival,CZE,Vlasim,D,1978-09-03 01:00:00,unknown,185.42,95.254320,R
2,8476906,Shayne,Gostisbehere,USA,Pembroke Pines,D,1993-04-20 01:00:00,FL,180.34,81.646560,L
3,8466285,Brian,Campbell,CAN,Strathroy,D,1979-05-23 01:00:00,ON,177.80,87.089664,L
4,8470607,Brent,Seabrook,CAN,Richmond,D,1985-04-20 01:00:00,BC,190.50,99.790240,R

In [112]:
#save file locally

df_clean_player_info.to_csv(r"C:\Users\zacle\Desktop\Serene\Project\NHL\ETL\clean\player_info.csv", index=False)

In [114]:
check_player_info = pd.read_csv(r"C:\Users\zacle\Desktop\Serene\Project\NHL\ETL\clean\player_info.csv")

In [116]:
check_player_info.dtypes

player_id                 int64
first_name               object
last_name                object
nationality              object
birth_city               object
primary_position         object
birth_date               object
birth_state_province     object
height_cm               float64
weight_kg               float64
shoots_catches           object
dtype: object